#-------------------------------------------------------------------------------
#
# GitHub Actions Test Configuration
#
#-------------------------------------------------------------------------------
---
name: "Test"

on:
  schedule:
    # 11pm UTC (9am Brisbane)
    - cron: "0 23 * * *"
  pull_request: {}
  push:
    branches:
      - "master"

env:
  CI: true
  CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"

jobs:
  test:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v1"

      - name: "Use Node.js 12.x"
        uses: "actions/setup-node@v1"
        with:
          node-version: "12.x"

      - name: "Install"
        run: "yarn install --no-audit"

      - name: "Verify"
        run: "yarn lint"

      - uses: "shivammathur/setup-php@master"
        with:
          php-version: "7.3"
          coverage: "xdebug"
      - name: "Install"
        run: "composer install"

      - name: "Verify"
        run: "composer run-script test:coverage && bash <(curl -s https://codecov.io/bash)"
